modLoader="javafml"
loaderVersion="[44,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/Mechalopa/Just-a-Few-Ohana/issues"
[[mods]]
modId="jafohana"
version="${file.jarVersion}"
displayName="Just a Few Ohana"
updateJSONURL="https://github.com/Mechalopa/Just-a-Few-Ohana/raw/1.19.3/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/just-a-few-ohana"
#logoFile="logo.png"
credits="Mechalopa"
authors="Mechalopa"
description='''More new flowers.'''
itemIcon="jafohana:dayflower"
[[dependencies.jafohana]]
    modId="forge"
    mandatory=true
    versionRange="[44.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jafohana]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"